export const DOCUMENT_CREATE_REQUEST = 'DOCUMENT_CREATE_REQUEST'
export const DOCUMENT_CREATE_SUCCESS = 'DOCUMENT_CREATE_SUCCESS'
export const DOCUMENT_CREATE_FAIL = 'DOCUMENT_CREATE_FAIL'

export const DOCUMENT_DELETE_REQUEST = 'DOCUMENT_DELETE_REQUEST'
export const DOCUMENT_DELETE_SUCCESS = 'DOCUMENT_DELETE_SUCCESS'
export const DOCUMENT_DELETE_FAIL = 'DOCUMENT_DELETE_FAIL'

export const DOCUMENT_REQUEST = 'DOCUMENT_REQUEST'
export const DOCUMENT_SUCCESS = 'DOCUMENT_SUCCESS'
export const DOCUMENT_FAIL = 'DOCUMENT_FAIL'

export const DOCUMENT_FILE_CREATE_REQUEST = 'DOCUMENT_FILE_CREATE_REQUEST'
export const DOCUMENT_FILE_CREATE_SUCCESS = 'DOCUMENT_FILE_CREATE_SUCCESS'
export const DOCUMENT_FILE_CREATE_FAIL = 'DOCUMENT_FILE_CREATE_FAIL'

export const DOCUMENT_FILE_DELETE_REQUEST = 'DOCUMENT_FILE_DELETE_REQUEST'
export const DOCUMENT_FILE_DELETE_SUCCESS = 'DOCUMENT_FILE_DELETE_SUCCESS'
export const DOCUMENT_FILE_DELETE_FAIL = 'DOCUMENT_FILE_DELETE_FAIL'
